/* Check the published Pages build through its real browser origin. All saves stay in isolated test contexts. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const OUT=process.env.AQUARIUM_ARTIFACTS||path.resolve('artifacts/aquarium-v02'),BASE=process.env.AQUARIUM_BASE_URL||'https://ff41009tw52-rgb.github.io/mimi-cream-farm/';
(async()=>{fs.mkdirSync(OUT,{recursive:true});const b=await chromium.launch({headless:true,executablePath:process.env.AQUARIUM_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']});const errors=[],failed=[],results=[];const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()});});};
const c=await b.newContext({viewport:{width:1440,height:960},hasTouch:true});const p=await c.newPage();watch(p);const response=await p.goto(BASE+'aquarium-v0.2.html?debug=1');assert.equal(response.status(),200);let d=await p.evaluate(()=>aquariumDebug());assert.equal(d.state.schemaVersion,2);assert.equal(d.state.coins,20);assert.equal(d.state.fishes.length,3);assert.equal(Object.keys(d.species).length,10);assert.equal(d.config.TEST_MODE,false);await p.screenshot({path:path.join(OUT,'online-main.png'),fullPage:true});results.push({test:'published-normal-start',passed:true});
// Same-origin native V0.1 -> V0.2 migration.
const mc=await b.newContext({viewport:{width:1440,height:960},hasTouch:true});const mp=await mc.newPage();watch(mp);assert.equal((await mp.goto(BASE+'aquarium-game.html')).status(),200);const old=JSON.parse(await mp.evaluate(()=>localStorage.getItem('aquarium_game_save_v1')));assert.equal(old.coins,120);await mp.goto(BASE+'aquarium-v0.2.html?debug=1');d=await mp.evaluate(()=>aquariumDebug());assert.equal(d.state.coins,120);assert.deepEqual(d.state.fishes.map(f=>[f.id,f.name]),old.fishes.map(f=>[f.id,f.name]));const retained=await mp.evaluate(()=>localStorage.getItem('aquarium_game_save_v1'));
await mp.locator('#shop').click();await mp.locator('[data-species="guppy"]').click();await mp.locator('#dialog-close').click();assert.equal((await mp.evaluate(()=>aquariumDebug())).state.fishes.length,4);
await mp.locator('#roster').click();await mp.locator('.roster-item').first().click();await mp.locator('#rename').click();await mp.locator('#fish-new-name').fill('悠悠一號');await mp.getByRole('button',{name:'保存名字'}).click();await mp.locator('#close-card').click();await mp.locator('#shop').click();await mp.locator('#tab-decor').click();await mp.locator('[data-buy-decor="smallplant"]').click();await mp.locator('[data-place-decor="smallplant"]').click();await mp.getByRole('button',{name:'中央 · 0/2',exact:true}).click();await mp.locator('#dialog-close').click();await mp.reload();d=await mp.evaluate(()=>aquariumDebug());assert.equal(d.state.coins,20);assert.equal(d.state.fishes[0].name,'悠悠一號');assert(d.state.placedDecorations.some(x=>x.decoration==='smallplant'&&x.zone==='center'));assert.equal(await mp.evaluate(()=>localStorage.getItem('aquarium_game_save_v1')),retained);await mp.goto(BASE+'aquarium-v0.2-standalone.html?debug=1');assert.equal((await mp.evaluate(()=>aquariumDebug())).state.fishes[0].name,'悠悠一號');results.push({test:'published-v01-migration-buy-rename-decor-refresh-standalone',passed:true});await mc.close();
for(const size of [{width:1024,height:768},{width:820,height:1180}]){const tc=await b.newContext({viewport:size,hasTouch:true});const tp=await tc.newPage();watch(tp);await tp.goto(BASE+'aquarium-v0.2.html');assert(await tp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const id of ['feed','shop','clean']){const rect=await tp.locator('#'+id).boundingBox();assert(rect.width>=44&&rect.height>=44&&rect.y+rect.height<=size.height);}await tp.locator('#shop').tap();await tp.locator('#tab-decor').tap();await tp.locator('#dialog-close').tap();await tp.locator('#encyclopedia').tap();await tp.locator('#dialog-close').tap();await tp.screenshot({path:path.join(OUT,'online-'+size.width+'.png'),fullPage:true});results.push({test:'published-touch-'+size.width+'x'+size.height,passed:true});await tc.close();}
assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync(path.join(OUT,'online-results.json'),JSON.stringify({at:new Date().toISOString(),base:BASE,browser:b.version(),results,errors,failedRequests:failed},null,2));console.log('PASS published start, migration/save/rename/decor, standalone and both tablets');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
