/* Real Chromium regression tests. Animation and balancing use the real game simulation;
   Playwright clock accelerates time, fixtures isolate expensive-to-reach states. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const ROOT=path.resolve(__dirname,'../..'),OUT=process.env.AQUARIUM_ARTIFACTS||path.resolve('artifacts/aquarium-v02'),KEY='aquarium_game_save_v2',LEGACY='aquarium_game_save_v1';
const server=http.createServer((req,res)=>{const file=path.join(ROOT,decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(ROOT+path.sep))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(data);});});
server.listen(8771,'127.0.0.1');const URL='http://127.0.0.1:8771/aquarium-v0.2.html?debug=1';
(async()=>{
 fs.mkdirSync(OUT,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.AQUARIUM_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']});const errors=[],results=[];
 const pass=(name,details)=>{results.push({name,passed:true,details});console.log('PASS',name,details||'');};
 const read=p=>p.evaluate(()=>aquariumDebug());
 async function create({size={width:1440,height:960},state,key=KEY,seed={},url=URL,clock=true}={}){const context=await browser.newContext({viewport:size,deviceScaleFactor:1,hasTouch:true});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));if(state!==undefined)seed={...seed,[key]:typeof state==='string'?state:JSON.stringify(state)};await p.addInitScript(values=>{if(!sessionStorage.getItem('seeded')){for(const[k,v]of Object.entries(values))localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));sessionStorage.setItem('seeded','1');}Math.random=(()=>{let seed=812;return()=>{seed=seed*16807%2147483647;return seed/2147483647;};})();},seed);if(clock)await p.clock.install();await p.goto(url);if(clock)await p.clock.pauseAt(new Date(Date.now()+600));return {p,context};}
 async function advance(p,ms){await p.clock.runFor(ms);}
 const screenshot=(p,name)=>p.screenshot({path:path.join(OUT,name+'.png'),fullPage:true});
 async function closeDialog(p){await p.locator('#dialog-close').click();}
 async function shop(p,tab='fish'){await p.locator('#shop').click();await p.locator('#tab-'+tab).click();}
 async function settings(p){await p.locator('#settings').click();}
 async function selectFirst(p){await p.locator('#roster').click();await p.locator('.roster-item').first().click();}
 // Test 1: normal game starts with just 20 coins; earn the first new fish in 3–6 minutes.
 const fresh=await create();const p=fresh.p;let d,r;let initial=(await read(p)).state;assert.equal(initial.fishes.length,3);assert.equal(initial.coins,20);assert.equal(initial.schemaVersion,2);assert.equal(Object.keys((await read(p)).species).length,10);await screenshot(p,'01-main');
 if(!process.env.AQUARIUM_SKIP_ECONOMY){
 await shop(p);assert.equal(await p.locator('.buy:enabled').count(),3);assert.match(await p.locator('[data-species="angel"]').innerText(),/Lv.4/);await closeDialog(p);await p.locator('#feed').click();r=await p.locator('#tank').boundingBox();for(const x of [.25,.5,.75]){await p.touchscreen.tap(r.x+x*r.width,r.y+60);await advance(p,700);}await p.locator('#stop-feed').click();
 let firstAffordable=null;const economyTrace=[];for(let i=1;i<=12;i++){await advance(p,30000);if(await p.locator('#collect-all').isVisible())await p.locator('#collect-all').click();const d=await read(p);economyTrace.push({seconds:i*30,coins:d.state.coins,xp:d.state.xp,level:d.state.level,water:d.state.waterQuality,growth:d.state.fishes.map(f=>({species:f.species,growth:f.growth}))});if(d.state.coins>=d.species.guppy.price){firstAffordable=i*30;break;}console.log('ECONOMY',i*30,'seconds',d.state.coins,'coins');}
 assert(firstAffordable>=180&&firstAffordable<=360,`first affordability ${firstAffordable}`);d=await read(p);assert(d.diagnostics.eaten>0);assert(d.state.fishes[0].growthStage==='亞成魚');await shop(p);await p.locator('[data-species="guppy"]').click();await closeDialog(p);assert.equal((await read(p)).state.fishes.length,4);pass('Test 1：正式開局、餵食、收幣與第一隻新魚',{seconds:firstAffordable,eaten:d.diagnostics.eaten});fs.writeFileSync(path.join(OUT,'economy.json'),JSON.stringify({firstAffordable,eaten:d.diagnostics.eaten,trace:economyTrace},null,2));
 await p.reload();assert.equal((await read(p)).state.fishes.length,4);pass('購魚後 Auto Save 與刷新保留');await fresh.context.close();
 }else await fresh.context.close();
 // Test 7: import V0.1 source without touching its automatic or manual keys.
 const legacy={schemaVersion:1,gameVersion:'0.1',savedAt:Date.now(),coins:333,waterQuality:76,tankCapacity:10,fishes:initial.fishes.map((f,i)=>({...f,name:['小彩 Chen1','小金','小點'][i],growth:[42,83,100][i],hunger:[59,78,92][i],coinProgress:12})),drops:[{id:'old-coin',x:.4,y:.5,value:3}]};
 const legacyText=JSON.stringify(legacy);const migrated=await create({seed:{[LEGACY]:legacyText,[LEGACY+'_manual']:legacyText,'farm_tycoon_save_v2':'farm-sentinel'}});d=await read(migrated.p);assert.equal(d.state.schemaVersion,2);assert.equal(d.state.coins,333);assert.equal(d.state.tankCapacity,10);assert.equal(d.state.fishes.length,3);assert.deepEqual(d.state.fishes.map(f=>f.id),legacy.fishes.map(f=>f.id));assert.deepEqual(d.state.fishes.map(f=>f.name),legacy.fishes.map(f=>f.name));for(let i=0;i<3;i++){assert(Math.abs(d.state.fishes[i].growth-legacy.fishes[i].growth)<.2);assert(Math.abs(d.state.fishes[i].hunger-legacy.fishes[i].hunger)<.2);}assert(Math.abs(d.state.waterQuality-76)<.1);assert.equal(d.state.collection.cory.highestStage,2);assert.equal(await migrated.p.evaluate(k=>localStorage.getItem(k),LEGACY),legacyText);assert.equal(await migrated.p.evaluate(k=>localStorage.getItem(k),LEGACY+'_manual'),legacyText);assert.equal(JSON.parse(await migrated.p.evaluate(k=>localStorage.getItem(k),KEY+'_manual')).schemaVersion,2);pass('Test 7：V0.1 自動與手動存檔 migration，原檔與農場存檔保持完整');
 const base=(await read(migrated.p)).state;await migrated.context.close();
 function fixture(){const f=structuredClone(base);f.savedAt=Date.now();f.cleanReadyAt=0;f.coins=12000;f.xp=620;f.level=5;return f;}
 // Test 4: buy, place and switch through actual shop controls; detect occupied slots.
 const decorating=await create({state:fixture()});await shop(decorating.p,'decor');await decorating.p.locator('[data-buy-decor="white"]').click();await decorating.p.locator('[data-buy-decor="tallplant"]').click();await decorating.p.locator('[data-place-decor="tallplant"]').click();await decorating.p.getByRole('button',{name:'左側 · 1/2',exact:true}).click();await decorating.p.locator('[data-buy-decor="wood"]').click();await decorating.p.locator('[data-place-decor="wood"]').click();await decorating.p.getByRole('button',{name:'中央 · 1/2',exact:true}).click();let saved=(await read(decorating.p)).state;assert.equal(saved.substrate,'white');assert(saved.placedDecorations.some(d=>d.decoration==='wood'&&d.zone==='center'));assert(saved.placedDecorations.some(d=>d.decoration==='tallplant'&&d.zone==='left'));await decorating.p.reload();d=await read(decorating.p);assert.deepEqual(d.state.placedDecorations,saved.placedDecorations);assert.deepEqual(d.state.purchasedDecorations,saved.purchasedDecorations);assert.equal(d.state.substrate,'white');pass('Test 4：裝飾購買、左／中央位置、底砂與刷新保留');
 await shop(decorating.p,'decor');await decorating.p.locator('[data-buy-decor="tallplant"]').click();await decorating.p.locator('[data-place-decor="tallplant"]').click();await decorating.p.getByRole('button',{name:'左側 · 2/2',exact:true}).click();assert.match(await decorating.p.locator('.shop-intro').innerText(),/位置已滿/);assert.equal((await read(decorating.p)).state.placedDecorations.length,saved.placedDecorations.length);await closeDialog(decorating.p);pass('裝飾衝突提示，不覆寫已放置物件');await decorating.context.close();
 // Test 5 and 6: first discovery once; rename validates input; sound preference survives reload.
 const collect=await create({state:fixture()});await shop(collect.p);await collect.p.locator('[data-species="angel"]').click();assert.equal((await read(collect.p)).diagnostics.discoveries,1);await collect.p.locator('[data-species="angel"]').click();assert.equal((await read(collect.p)).diagnostics.discoveries,1);assert.equal((await read(collect.p)).state.collection.angel.total,2);await closeDialog(collect.p);await collect.p.locator('#encyclopedia').click();assert.match(await collect.p.locator('[data-entry="angel"]').innerText(),/曾養 2 隻/);assert.match(await collect.p.locator('[data-entry="betta"]').innerText(),/已解鎖/);await closeDialog(collect.p);pass('Test 5：首次取得圖鑑發現、重複購買不重播');
 await selectFirst(collect.p);await screenshot(collect.p,'06-fish-info');await collect.p.locator('#rename').click();await collect.p.locator('#fish-new-name').fill('   ');await collect.p.getByRole('button',{name:'保存名字'}).click();assert.match(await collect.p.locator('#name-error').innerText(),/不能/);await collect.p.locator('#fish-new-name').fill('<b>魚</b>');await collect.p.getByRole('button',{name:'保存名字'}).click();assert.match(await collect.p.locator('#name-error').innerText(),/HTML/);await collect.p.locator('#fish-new-name').fill('這是超過十二個字的名字測試用');await collect.p.getByRole('button',{name:'保存名字'}).click();assert.match(await collect.p.locator('#name-error').innerText(),/12/);await collect.p.locator('#fish-new-name').fill('小星 Chen12');await screenshot(collect.p,'06-rename');await collect.p.getByRole('button',{name:'保存名字'}).click();await collect.p.reload();assert.equal((await read(collect.p)).state.fishes[0].name,'小星 Chen12');pass('Test 6：中英數命名、空白／超長／HTML 拒絕、刷新保留');
 await settings(collect.p);await collect.p.getByRole('button',{name:'關閉',exact:true}).click();await closeDialog(collect.p);await collect.p.reload();assert.equal((await read(collect.p)).state.soundEnabled,false);pass('音效由首次操作啟用、音效設定保存');
 await selectFirst(collect.p);const total=(await read(collect.p)).state.collection.guppy.total;await collect.p.locator('#rehome').click();await collect.p.getByRole('button',{name:'確認送養'}).click();assert.equal((await read(collect.p)).state.collection.guppy.total,total);assert.equal((await read(collect.p)).state.fishes.length,4);pass('送養保留圖鑑紀錄，容量可留給新魚種');await collect.context.close();
 // Cleaning: threshold, animated gradual result, cooldown, save.
 const dirtyState=fixture();dirtyState.waterQuality=32;const dirty=await create({state:dirtyState});await screenshot(dirty.p,'07-dirty');await dirty.p.locator('#clean').click();await advance(dirty.p,800);d=await read(dirty.p);assert(d.cleaning&&d.state.waterQuality>32&&d.state.waterQuality<70);await screenshot(dirty.p,'08-clean-animation');await advance(dirty.p,1600);d=await read(dirty.p);assert(!d.cleaning&&d.state.waterQuality>69&&d.state.waterQuality<=70);assert(d.state.cleanReadyAt>Date.now());await dirty.p.locator('#clean').click();assert.match(await dirty.p.locator('#toast').innerText(),/再等/);await screenshot(dirty.p,'08-clean-after');await dirty.p.reload();assert((await read(dirty.p)).state.waterQuality>69);pass('清潔兩秒漸變、泡泡動畫、45 秒冷卻、刷新不洗掉冷卻');await dirty.context.close();
 const cleanState=fixture();cleanState.waterQuality=100;const clean=await create({state:cleanState});await clean.p.locator('#clean').click();assert.match(await clean.p.locator('#toast').innerText(),/不需要/);assert(!(await read(clean.p)).cleaning);await clean.context.close();pass('高水質不重複清潔');
 // Test 2 / 3: all ten species, ten decorations, food and coins at once. No clock for actual FPS measurement.
 const crowd=fixture();const species=(await create()).p;const defs=(await read(species)).species;await species.context().close();crowd.fishes=Object.entries(defs).map(([id,s],i)=>({id:'crowd-'+id,species:id,name:s.nickname,growth:[10,50,100][i%3],hunger:55,growthStage:'幼魚',size:s.size,createdAt:Date.now()-240000,coinProgress:0}));crowd.collection=Object.fromEntries(crowd.fishes.map(f=>[f.species,{total:1,highestStage:f.growth>=100?2:f.growth>=35?1:0}]));crowd.purchasedDecorations={river:1,white:1,black:1,smallplant:2,tallplant:2,moss:1,smallrock:1,bigrock:1,wood:1,cave:1,chest:1};crowd.placedDecorations=[['tallplant','left','back1'],['smallplant','left','back2'],['bigrock','left','floor1'],['cave','left','floor2'],['moss','center','back1'],['smallplant','center','back2'],['smallrock','center','floor1'],['chest','center','floor2'],['tallplant','right','back1'],['wood','right','floor1']].map(([decoration,zone,slot],i)=>({id:'decor-'+i,decoration,zone,slot}));crowd.substrate='white';crowd.drops=[{id:'c1',x:.3,y:.5,value:6},{id:'c2',x:.6,y:.8,value:10}];
 const stress=await create({state:crowd,clock:false});await screenshot(stress.p,'02-ten-fish');await shop(stress.p);await screenshot(stress.p,'03-shop-fish');await stress.p.locator('#tab-decor').click();await screenshot(stress.p,'04-shop-decor');await closeDialog(stress.p);await stress.p.locator('#encyclopedia').click();await screenshot(stress.p,'05-encyclopedia');await closeDialog(stress.p);
 await stress.p.locator('#feed').click();r=await stress.p.locator('#tank').boundingBox();await stress.p.locator('#food-type').selectOption('normal');for(const x of [.15,.3,.45,.6,.75,.9]){await stress.p.touchscreen.tap(r.x+r.width*x,r.y+45);await new Promise(resolve=>setTimeout(resolve,750));}const stressStart=await read(stress.p);assert(stressStart.food.length>0&&stressStart.state.drops.length>0);
 const performanceResult=await stress.p.evaluate(async()=>{const intervals=[],samples=[];let last;const begin=performance.now();await new Promise(resolve=>{function tick(t){if(last)intervals.push(t-last);last=t;if(samples.length<30)samples.push(aquariumDebug().runtime.map(r=>({id:r.id,x:r.x,y:r.y,vx:r.vx,vy:r.vy})));if(performance.now()-begin<4000)requestAnimationFrame(tick);else resolve();}requestAnimationFrame(tick);});intervals.sort((a,b)=>a-b);const d=aquariumDebug();return {fps:1000/(intervals.reduce((a,b)=>a+b,0)/intervals.length),p95:intervals[Math.floor(intervals.length*.95)],max:Math.max(...intervals),costMax:d.diagnostics.costMax,costMean:d.diagnostics.costTotal/d.diagnostics.frames,fish:d.state.fishes.length,decor:d.state.placedDecorations.length,food:d.food.length,coins:d.state.drops.length,runtime:d.runtime,species:d.species,samples};});
 assert.equal(performanceResult.fish,10);assert.equal(performanceResult.decor,10);assert(performanceResult.fps>28);assert(performanceResult.coins>0);performanceResult.foodAtStart=stressStart.food.length;performanceResult.coinsAtStart=stressStart.state.drops.length;for(const item of performanceResult.runtime){assert(item.x>.03&&item.x<.97&&item.y>.09&&item.y<.95);if(item.id==='crowd-cory')assert(item.y>.75);}assert(performanceResult.species.guppy.speed>performanceResult.species.goldfish.speed*2);assert(performanceResult.species.zebra.schoolingStrength>0);assert(performanceResult.species.angel.turnSpeed<performanceResult.species.guppy.turnSpeed);pass('Test 2 / 3：十種外形與資料驅動行為、十魚＋十裝飾＋餵食＋金幣效能',{fps:Math.round(performanceResult.fps),p95Ms:+performanceResult.p95.toFixed(2),simulationAndDrawMeanMs:+performanceResult.costMean.toFixed(2),simulationAndDrawMaxMs:+performanceResult.costMax.toFixed(2)});fs.writeFileSync(path.join(OUT,'performance.json'),JSON.stringify(performanceResult,null,2));await stress.context.close();
 // Test 8: both required tablets plus phone. Touch opening, tab switch, collection and card close.
 for(const size of [{width:1024,height:768},{width:820,height:1180},{width:390,height:844}]){const tablet=await create({size,state:crowd});assert(await tablet.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));let box=await tablet.p.locator('#tank').boundingBox();assert(box.x+box.width<=size.width);assert(box.height>=size.height*(size.width===820?.54:.4));for(const id of ['feed','shop','clean']){box=await tablet.p.locator('#'+id).boundingBox();assert(box.width>=44&&box.height>=44&&box.y+box.height<=size.height);}await screenshot(tablet.p,size.width===1024?'09-tablet-1024':size.width===820?'10-tablet-820':'11-phone');await shop(tablet.p,'decor');assert(await tablet.p.locator('#tab-fish').isVisible());await tablet.p.locator('[data-buy-decor="smallrock"]').click();await tablet.p.locator('[data-place-decor="smallrock"]').click();await tablet.p.getByRole('button',{name:'右側 · 1/2',exact:true}).click();assert((await read(tablet.p)).state.placedDecorations.some(d=>d.decoration==='smallrock'&&d.zone==='right'));await closeDialog(tablet.p);await tablet.p.locator('#encyclopedia').click();await closeDialog(tablet.p);await selectFirst(tablet.p);box=await tablet.p.locator('#fish-card').boundingBox();const tank=await tablet.p.locator('#tank').boundingBox();assert(box.height<tank.height&&box.width<tank.width*.6);await tablet.p.locator('#close-card').click();assert(!(await tablet.p.locator('#fish-card').isVisible()));await tablet.context.close();pass(`Test 8：${size.width}×${size.height} 商店、圖鑑、資訊卡、觸控與版面`);}
 // Unknown / corrupt saves are protected, test mode isolated and accelerated, legacy reset unaffected.
 for(const bad of ['{bad',JSON.stringify({...base,schemaVersion:99}),JSON.stringify({...base,placedDecorations:[{id:'bad',decoration:'ship',zone:'left',slot:'back1'}]})]){const broken=await create({state:bad});assert((await read(broken.p)).saveBlocked);await advance(broken.p,16000);assert.equal(await broken.p.evaluate(k=>localStorage.getItem(k),KEY),bad);await broken.context.close();}pass('損壞、未知 schema 與非法布置不覆蓋原檔');
 const quota=await browser.newContext();const qp=await quota.newPage();qp.on('pageerror',e=>errors.push(e.message));await qp.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('full','QuotaExceededError');};});await qp.goto(URL);assert.match(await qp.locator('#save-status').innerText(),/無法儲存/);assert(await qp.locator('#feed').isEnabled());await quota.close();pass('localStorage 空間不足仍可遊玩');
 const testing=await create({url:'http://127.0.0.1:8771/aquarium-v0.2.html?test=1',seed:{[KEY]:JSON.stringify(base),[LEGACY]:legacyText}});assert.equal((await read(testing.p)).config.SAVE_KEY,'aquarium_game_save_v2_test');await advance(testing.p,15000);d=await read(testing.p);assert(d.state.fishes[0].growth>50);assert(await testing.p.evaluate(k=>localStorage.getItem(k),KEY)===JSON.stringify(base));assert.equal(await testing.p.evaluate(k=>localStorage.getItem(k),LEGACY),legacyText);pass('測試模式加速成長、收益、解鎖，正式與 V0.1 存檔隔離');await testing.context.close();
 const reset=await create({state:fixture(),seed:{[LEGACY]:legacyText,[LEGACY+'_manual']:legacyText,'farm_tycoon_save_v2':'farm-sentinel'}});await settings(reset.p);await reset.p.getByRole('button',{name:'存檔',exact:true}).click();await settings(reset.p);await reset.p.getByRole('button',{name:'重置',exact:true}).click();await reset.p.getByRole('button',{name:'確認重置'}).click();assert.equal((await read(reset.p)).state.coins,12000);await reset.p.getByRole('button',{name:'確認重置'}).click();assert.equal((await read(reset.p)).state.coins,20);assert.equal(await reset.p.evaluate(k=>localStorage.getItem(k),LEGACY),legacyText);assert.equal(await reset.p.evaluate(()=>localStorage.getItem('farm_tycoon_save_v2')),'farm-sentinel');pass('V0.2 二次確認重置不影響 V0.1／農場');await reset.context.close();
 assert.deepEqual(errors,[]);pass('無未捕捉瀏覽器例外');fs.writeFileSync(path.join(OUT,'test-results.json'),JSON.stringify({at:new Date().toISOString(),browser:browser.version(),results,errors},null,2));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1);});
