const {harness}=require('./v03-harness.cjs'),assert=require('node:assert/strict');
(async()=>{const h=await harness(8785),{create,read,pass,advance,KEY}=h;
 // A former V0.2 Lv.5 must retain XP 620 and all previously earned unlocks.
 const old=h.legacy();old.level=5;old.xp=620;const veteran=await create({seed:{aquarium_game_save_v2:JSON.stringify(old)}});assert.equal((await read(veteran.p)).state.level,5);assert.equal((await read(veteran.p)).state.xp,620);await advance(veteran.p,61000);assert.equal((await read(veteran.p)).state.level,5);await veteran.p.reload();assert.equal((await read(veteran.p)).state.level,5);await veteran.context.close();pass('V0.2 Lv.5 / XP 620 既得解鎖保留，XP 成長與刷新不降級');
 const good=h.legacy(),text=JSON.stringify(good);const manual=await create({seed:{aquarium_game_save_v2:text,aquarium_game_save_v2_manual:'{bad'}});assert(!(await read(manual.p)).saveBlocked);assert.equal(await manual.p.evaluate(()=>localStorage.getItem('aquarium_game_save_v2_manual')),'{bad');assert.equal(await manual.p.evaluate(k=>localStorage.getItem(k+'_manual'),KEY),null);await manual.context.close();pass('損壞舊手動快照保留，合法自動進度仍可升級');
 const quota=await h.browser.newContext();const p=await quota.newPage();p.on('pageerror',e=>h.errors.push(e.message));await p.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('full','QuotaExceededError');};});await p.goto('http://127.0.0.1:8785/aquarium-v0.3.html?debug=1');assert.match(await p.locator('#save-status').innerText(),/無法儲存/);assert(await p.locator('#feed').isEnabled());await quota.close();pass('儲存空間不足仍可遊玩，顯示保存失敗');
 const seed=await create();const state=(await read(seed.p)).state;await seed.context.close();state.savedAt=Date.now();state.coins=200;state.stats.purchases=1;state.onboarding={completed:true,skipped:false,step:3};const recovery=await create({state:'{bad',seed:{[KEY+'_manual']:'{bad'}});assert((await read(recovery.p)).saveBlocked);await recovery.p.locator('#settings').click();await recovery.p.getByRole('button',{name:'讀檔',exact:true}).click();await recovery.p.getByRole('button',{name:'確定讀取',exact:true}).click();assert((await read(recovery.p)).saveBlocked);assert.equal(await recovery.p.evaluate(k=>localStorage.getItem(k),KEY),'{bad');await recovery.p.evaluate(({key,state})=>localStorage.setItem(key+'_manual',JSON.stringify(state)),{key:KEY,state});await recovery.p.locator('#settings').click();await recovery.p.getByRole('button',{name:'讀檔',exact:true}).click();await recovery.p.getByRole('button',{name:'確定讀取',exact:true}).click();assert(!(await read(recovery.p)).saveBlocked);assert.equal((await read(recovery.p)).state.coins,state.coins);assert.equal(JSON.parse(await recovery.p.evaluate(k=>localStorage.getItem(k),KEY)).saveId,state.saveId);await recovery.p.locator('#roster').click();await recovery.p.locator('.roster-item').first().click();await recovery.p.locator('#rename').click();await recovery.p.locator('#fish-new-name').fill('復原小魚');await recovery.p.getByRole('button',{name:'保存名字'}).click();await recovery.p.reload();assert(!(await read(recovery.p)).saveBlocked);assert.equal((await read(recovery.p)).state.fishes[0].name,'復原小魚');await recovery.context.close();pass('損壞自動檔拒絕無效手動備份；明確確認有效手動備份後恢復保存，後續改名與刷新不丟進度');
 const recoveryQuota=await create({state:'{bad',seed:{[KEY+'_manual']:JSON.stringify(state)}});
 assert((await read(recoveryQuota.p)).saveBlocked);
 await recoveryQuota.p.evaluate(key=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k===key)throw new DOMException('full','QuotaExceededError');return original.call(this,k,v);};window.restoreTestStorage=()=>{Storage.prototype.setItem=original;};},KEY);
 await recoveryQuota.p.locator('#settings').click();await recoveryQuota.p.getByRole('button',{name:'讀檔',exact:true}).click();await recoveryQuota.p.getByRole('button',{name:'確定讀取',exact:true}).click();
 assert((await read(recoveryQuota.p)).saveBlocked);assert.equal(await recoveryQuota.p.evaluate(k=>localStorage.getItem(k),KEY),'{bad');assert.match(await recoveryQuota.p.locator('#toast').innerText(),/目前無法儲存/);assert.doesNotMatch(await recoveryQuota.p.locator('#toast').innerText(),/✓/);
 await recoveryQuota.p.evaluate(()=>restoreTestStorage());await recoveryQuota.p.locator('#settings').click();await recoveryQuota.p.getByRole('button',{name:'讀檔',exact:true}).click();await recoveryQuota.p.getByRole('button',{name:'確定讀取',exact:true}).click();assert(!(await read(recoveryQuota.p)).saveBlocked);await recoveryQuota.p.reload();assert(!(await read(recoveryQuota.p)).saveBlocked);assert.equal((await read(recoveryQuota.p)).state.coins,state.coins);await recoveryQuota.context.close();pass('有效手動復原遇寫入失敗仍保留保存鎖與原檔、不顯示成功；儲存恢復後可重試並刷新');
 const rewards=await create({state});await rewards.p.locator('#tank-menu').click();await rewards.p.getByRole('button',{name:'永久成就',exact:true}).click();await rewards.p.evaluate(()=>{const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.includes('_rewards_'))throw new DOMException('full','QuotaExceededError');return original.call(this,k,v);};});const before=(await read(rewards.p)).state.coins;await rewards.p.locator('[data-claim="firstPurchase"]').click();assert.equal((await read(rewards.p)).state.coins,before);assert(!(await read(rewards.p)).state.achievements.firstPurchase.rewardClaimed);await rewards.context.close();pass('獎勵保存失敗時不給獎、不標記已領');
 const autosave=await create({cadence:100});const start=(await read(autosave.p)).diagnostics.writes;await advance(autosave.p,1000);assert.equal((await read(autosave.p)).diagnostics.writes,start);await advance(autosave.p,16000);assert((await read(autosave.p)).diagnostics.writes>start);const saved=JSON.parse(await autosave.p.evaluate(k=>localStorage.getItem(k),KEY));assert(saved.fishes.every(f=>!Object.hasOwn(f,'x')&&!Object.hasOwn(f,'target')&&!Object.hasOwn(f,'vx')));await autosave.context.close();pass('15 秒 dirty Auto Save、沒有每幀寫入、沒有魚的瞬間動畫資料');
 const reset=await create({seed:{aquarium_game_save_v2:text,aquarium_game_save_v1:'v1-sentinel','farm_tycoon_save_v2':'farm-sentinel'}});await reset.p.locator('#settings').click();await reset.p.getByRole('button',{name:'重置',exact:true}).click();await reset.p.getByRole('button',{name:'確認重置',exact:true}).click();await reset.p.getByRole('button',{name:'確認重置',exact:true}).click();assert.equal((await read(reset.p)).state.coins,20);assert.equal(await reset.p.evaluate(()=>localStorage.getItem('aquarium_game_save_v2')),text);assert.equal(await reset.p.evaluate(()=>localStorage.getItem('aquarium_game_save_v1')),'v1-sentinel');assert.equal(await reset.p.evaluate(()=>localStorage.getItem('farm_tycoon_save_v2')),'farm-sentinel');await reset.context.close();pass('V0.3 重置只處理本版本，V0.2/V0.1/其他遊戲完整');const imports=await create({state});const foreign=structuredClone(state);foreign.saveId='tank-corrupt-ledger';await imports.p.evaluate(({key,id})=>localStorage.setItem(key+'_rewards_'+id,'{bad'),{key:KEY,id:foreign.saveId});await imports.p.locator('#settings').click();await imports.p.getByRole('button',{name:'匯入',exact:true}).click();await imports.p.locator('#save-import-file').setInputFiles({name:'foreign.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(foreign))});await imports.p.getByRole('button',{name:'確定讀取',exact:true}).click();assert.equal((await read(imports.p)).state.saveId,state.saveId);assert.equal((await read(imports.p)).state.coins,state.coins);await imports.context.close();pass('匯入時領獎紀錄損壞：不更換目前進度、不拋 JS error');assert.deepEqual(h.errors,[]);h.saveResults('guard-results',{results:h.results,errors:h.errors});await h.close();})().catch(e=>{console.error(e);process.exit(1)});
