/* Real Chromium regression tests. Animation and balancing use the real game simulation;
   Playwright clock accelerates time, fixtures isolate expensive-to-reach states. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const ROOT=path.resolve(__dirname,'../..'),OUT=process.env.AQUARIUM_ARTIFACTS||path.resolve('artifacts/aquarium-v02'),KEY='aquarium_game_save_v2',LEGACY='aquarium_game_save_v1';
const server=http.createServer((req,res)=>{const file=path.join(ROOT,decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(ROOT+path.sep))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(data);});});
server.listen(8782,'127.0.0.1');const URL='http://127.0.0.1:8782/aquarium-v0.2.html?debug=1';
(async()=>{
 fs.mkdirSync(OUT,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.AQUARIUM_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']});const errors=[],results=[];
 const pass=(name,details)=>{results.push({name,passed:true,details});console.log('PASS',name,details||'');};
 const read=p=>p.evaluate(()=>aquariumDebug());
 async function create({size={width:1440,height:960},state,key=KEY,seed={},url=URL,clock=true}={}){const context=await browser.newContext({viewport:size,deviceScaleFactor:1,hasTouch:true});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));if(state!==undefined)seed={...seed,[key]:typeof state==='string'?state:JSON.stringify(state)};await p.addInitScript(values=>{if(!sessionStorage.getItem('seeded')){for(const[k,v]of Object.entries(values))localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));sessionStorage.setItem('seeded','1');}Math.random=(()=>{let seed=812;return()=>{seed=seed*16807%2147483647;return seed/2147483647;};})();},seed);if(clock)await p.clock.install();await p.goto(url);if(clock)await p.clock.pauseAt(new Date(Date.now()+600));return {p,context};}
 async function advance(p,ms){await p.clock.runFor(ms);}
 const screenshot=(p,name)=>p.screenshot({path:path.join(OUT,name+'.png'),fullPage:true});
 async function closeDialog(p){await p.locator('#dialog-close').click();}
 async function shop(p,tab='fish'){await p.locator('#shop').click();await p.locator('#tab-'+tab).click();}
 async function settings(p){await p.locator('#settings').click();}
 async function selectFirst(p){await p.locator('#roster').click();await p.locator('.roster-item').first().click();}

 const fresh=await create();const p=fresh.p;assert(!(await read(p)).config.TEST_MODE);const initial=(await read(p)).state;const trace=[],actions=[];const purchases=['guppy','zebra','molly','whitecloud','swordtail'];let purchaseIndex=0,firstPurchase=null,decor=false,sand=false;
 async function feedPair(){await p.locator('#feed').click();const box=await p.locator('#tank').boundingBox();await p.locator('#food-type').selectOption('normal');await p.touchscreen.tap(box.x+box.width*.25,box.y+150);await advance(p,750);await p.locator('#food-type').selectOption('sinking');await p.touchscreen.tap(box.x+box.width*.75,box.y+150);await advance(p,750);await p.locator('#stop-feed').click();}
 await feedPair();
 for(let seconds=30;seconds<=1200;seconds+=30){await advance(p,30000);let d=await read(p);if(d.state.drops.length)await p.locator('#collect-all').click();d=await read(p);
  if(seconds%120===0&&d.state.fishes.reduce((a,f)=>a+f.hunger,0)/d.state.fishes.length<72){await feedPair();actions.push({seconds,action:'feed'});}
  if(d.state.waterQuality<68){await p.locator('#clean').click();actions.push({seconds,action:'clean'});await advance(p,2500);}
  const id=purchases[purchaseIndex];d=await read(p);if(id&&d.state.coins>=d.species[id].price&&d.state.level>=d.species[id].unlockLevel){await shop(p);await p.locator(`[data-species="${id}"]`).click();await closeDialog(p);actions.push({seconds,action:'buy-fish',species:id,price:d.species[id].price});if(firstPurchase===null)firstPurchase=seconds;purchaseIndex++;}
  d=await read(p);if(seconds>=600&&!decor&&d.state.coins>=35){await shop(p,'decor');await p.locator('[data-buy-decor="smallplant"]').click();await p.locator('[data-place-decor="smallplant"]').click();await p.getByRole('button',{name:'中央 · 0/2',exact:true}).click();await closeDialog(p);decor=true;actions.push({seconds,action:'plant-center',price:35});}
  d=await read(p);if(seconds>=900&&!sand&&d.state.coins>=65){await shop(p,'decor');await p.locator('[data-buy-decor="white"]').click();await closeDialog(p);sand=true;actions.push({seconds,action:'white-sand',price:65});}
  d=await read(p);const sample={seconds,coins:d.state.coins,level:d.state.level,xp:d.state.xp,fish:d.state.fishes.length,water:+d.state.waterQuality.toFixed(1),eaten:d.diagnostics.eaten,decor:d.state.placedDecorations.length,substrate:d.state.substrate,fishes:d.state.fishes.map(f=>({species:f.species,growth:+f.growth.toFixed(2),stage:f.growthStage,hunger:+f.hunger.toFixed(1)}))};trace.push(sample);if(seconds%120===0)console.log('NORMAL PLAY',JSON.stringify(sample));if(seconds===600||seconds===1200)await screenshot(p,'normal-'+seconds+'-seconds');
 }
 const final=(await read(p)).state;assert(firstPurchase>=180&&firstPurchase<=360);assert(trace.find(t=>t.seconds===600).fish>=4);assert(final.fishes.length>=5);assert(decor&&sand);assert(final.fishes.find(f=>f.id===initial.fishes[0].id).growthStage==='成魚');assert(Object.keys(final.collection).length>=5);assert(final.waterQuality>=45);assert(!(await read(p)).saveBlocked);
 await p.locator('#settings').click();await p.getByRole('button',{name:'存檔',exact:true}).click();const saved=(await read(p)).state;await p.reload();const restored=(await read(p)).state;assert.deepEqual(restored.fishes.map(f=>[f.id,f.name]),saved.fishes.map(f=>[f.id,f.name]));assert.equal(restored.coins,saved.coins);assert.equal(restored.substrate,'white');assert.deepEqual(restored.placedDecorations,saved.placedDecorations);assert.deepEqual(restored.collection,saved.collection);assert.deepEqual(errors,[]);
 const evidence={at:new Date().toISOString(),mode:'normal',clock:'Playwright virtual clock, every actual simulation frame; normal configuration unchanged; user actions only',firstPurchase,trace,actions,final:saved,checks:{twentyMinutes:true,firstFishWithin3to6Minutes:true,expansionBy10Minutes:true,atLeast5FishAnd5SpeciesBy20Minutes:true,adultGuppy:true,placedDecoration:true,whiteSubstrate:true,refreshPersistence:true},errors};fs.writeFileSync(path.join(OUT,'normal-20-minute-results.json'),JSON.stringify(evidence,null,2));pass('完整二十分鐘正式模式養成、經濟、購魚、布置與刷新保存',{firstPurchase,fish:final.fishes.length,known:Object.keys(final.collection).length,level:final.level,coins:final.coins});await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1);});
