/* Real Chromium regression tests. Animation and balancing use the real game simulation;
   Playwright clock accelerates time, fixtures isolate expensive-to-reach states. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const ROOT=path.resolve(__dirname,'../..'),OUT=process.env.AQUARIUM_ARTIFACTS||path.resolve('artifacts/aquarium-v02'),KEY='aquarium_game_save_v2',LEGACY='aquarium_game_save_v1';
const server=http.createServer((req,res)=>{const file=path.join(ROOT,decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(ROOT+path.sep))return res.writeHead(403).end();fs.readFile(file,(err,data)=>{if(err)return res.writeHead(404).end();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html; charset=utf-8');res.end(data);});});
server.listen(8772,'127.0.0.1');const URL='http://127.0.0.1:8772/aquarium-v0.2.html?debug=1';
(async()=>{
 fs.mkdirSync(OUT,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.AQUARIUM_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage']});const errors=[],results=[];
 const pass=(name,details)=>{results.push({name,passed:true,details});console.log('PASS',name,details||'');};
 const read=p=>p.evaluate(()=>aquariumDebug());
 async function create({size={width:1440,height:960},state,key=KEY,seed={},url=URL,clock=true}={}){const context=await browser.newContext({viewport:size,deviceScaleFactor:1,hasTouch:true});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));if(state!==undefined)seed={...seed,[key]:typeof state==='string'?state:JSON.stringify(state)};await p.addInitScript(values=>{if(!sessionStorage.getItem('seeded')){for(const[k,v]of Object.entries(values))localStorage.setItem(k,typeof v==='string'?v:JSON.stringify(v));sessionStorage.setItem('seeded','1');}Math.random=(()=>{let seed=812;return()=>{seed=seed*16807%2147483647;return seed/2147483647;};})();},seed);if(clock)await p.clock.install();await p.goto(url);if(clock)await p.clock.pauseAt(new Date(Date.now()+600));return {p,context};}
 async function advance(p,ms){await p.clock.runFor(ms);}
 const screenshot=(p,name)=>p.screenshot({path:path.join(OUT,name+'.png'),fullPage:true});
 async function closeDialog(p){await p.locator('#dialog-close').click();}
 async function shop(p,tab='fish'){await p.locator('#shop').click();await p.locator('#tab-'+tab).click();}
 async function settings(p){await p.locator('#settings').click();}
 async function selectFirst(p){await p.locator('#roster').click();await p.locator('.roster-item').first().click();}

 const fresh=await create();const base=(await read(fresh.p)).state,defs=(await read(fresh.p)).species;await fresh.context.close();
 function fixture(){const f=structuredClone(base);f.savedAt=Date.now();f.coins=5000;f.xp=620;f.level=5;return f;}
 // A native V0.1-created save, not just an approximated fixture.
 const old=await create({url:'http://127.0.0.1:8772/aquarium-game.html?test=1'});await advance(old.p,1000);const oldText=await old.p.evaluate(()=>localStorage.getItem('aquarium_game_save_v1'));assert(oldText);const oldSave=JSON.parse(oldText);await old.context.close();const upgraded=await create({seed:{[LEGACY]:oldText}});let d=await read(upgraded.p);assert.equal(d.state.coins,oldSave.coins);assert.deepEqual(d.state.fishes.map(f=>[f.id,f.name]),oldSave.fishes.map(f=>[f.id,f.name]));assert.equal(await upgraded.p.evaluate(k=>localStorage.getItem(k),LEGACY),oldText);await upgraded.context.close();pass('實際由 V0.1 程式產生的存檔成功升級');
 const manual=await create({state:fixture()});await shop(manual.p,'decor');await manual.p.locator('[data-buy-decor="black"]').click();await closeDialog(manual.p);await settings(manual.p);await manual.p.getByRole('button',{name:'存檔',exact:true}).click();const remembered=(await read(manual.p)).state;await shop(manual.p);await manual.p.locator('[data-species="angel"]').click();await closeDialog(manual.p);await settings(manual.p);await manual.p.getByRole('button',{name:'讀檔',exact:true}).click();await manual.p.getByRole('button',{name:'確定讀取',exact:true}).click();d=await read(manual.p);assert.equal(d.state.fishes.length,remembered.fishes.length);assert.equal(d.state.coins,remembered.coins);assert.equal(d.state.substrate,'black');assert.deepEqual(d.state.collection,remembered.collection);assert.deepEqual(d.state.placedDecorations,remembered.placedDecorations);await manual.p.reload();assert.equal((await read(manual.p)).state.substrate,'black');pass('V0.2 手動快照讀回魚、金額、圖鑑、底砂與裝飾');
 // JSON import backs up current V0.2 only, validates before mutation.
 await settings(manual.p);await manual.p.getByRole('button',{name:'匯入',exact:true}).click();await manual.p.locator('#save-import-file').setInputFiles({name:'v01.json',mimeType:'application/json',buffer:Buffer.from(oldText)});await manual.p.getByRole('button',{name:'確定讀取',exact:true}).click();d=await read(manual.p);assert.equal(d.state.coins,oldSave.coins);assert.equal(JSON.parse(await manual.p.evaluate(k=>localStorage.getItem(k+'_before_import'),KEY)).substrate,'black');await settings(manual.p);await manual.p.getByRole('button',{name:'匯入',exact:true}).click();await manual.p.locator('#save-import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});assert.equal((await read(manual.p)).state.coins,oldSave.coins);pass('V0.1 JSON 匯入、V0.2 匯入前備份、非法 JSON 拒絕');await manual.context.close();
 const offlineState=fixture();offlineState.savedAt=Date.now()-8*3600000;offlineState.fishes.forEach(f=>{f.hunger=80;f.growth=0;});const away=await create({state:offlineState});d=await read(away.p);assert(d.state.coins>5000&&d.state.coins<=5120);assert(Math.abs(d.state.fishes[0].growth-24)<.2);assert(Math.abs(d.state.fishes[0].hunger-60)<.2);const before=d.state.coins;await away.p.reload();assert.equal((await read(away.p)).state.coins,before);pass('離線最多四小時、收益上限與刷新不可重領');await away.context.close();
 const tabs=await create({clock:false});const p2=await tabs.context.newPage();await p2.goto(URL);await tabs.p.waitForFunction(()=>aquariumDebug().conflict);const current=await p2.evaluate(k=>localStorage.getItem(k),KEY);await tabs.p.locator('#clean').click();assert.equal(await tabs.p.evaluate(k=>localStorage.getItem(k),KEY),current);await settings(tabs.p);await tabs.p.getByRole('button',{name:'讀取',exact:true}).click();await tabs.p.getByRole('button',{name:'確定讀取',exact:true}).click();assert(!(await read(tabs.p)).conflict);pass('多分頁衝突停止保存、明確重讀後恢复');await tabs.context.close();
 // One minute of actual simulation: fast / slow / bottom movement and pause / bursts.
 const life=fixture();life.fishes=['guppy','guppy','goldfish','cory','cory','zebra','zebra','angel','whitecloud','betta'].map((id,i)=>({id:'life-'+i,species:id,name:defs[id].nickname,growth:40,hunger:80,createdAt:Date.now(),coinProgress:0}));life.collection={};for(const f of life.fishes){const c=life.collection[f.species]||(life.collection[f.species]={total:0,highestStage:1});c.total++;}const behavior=await create({state:life});const samples=[];for(let i=0;i<45;i++){await advance(behavior.p,1000);d=await read(behavior.p);samples.push({seconds:i+1,fish:d.runtime.map(r=>({id:r.id,x:r.x,y:r.y,speed:Math.hypot(r.vx,r.vy),pause:r.pause,burst:r.burst,behavior:r.behavior}))});}const avg=id=>samples.reduce((n,s)=>n+s.fish.find(f=>f.id===id).speed,0)/samples.length;assert(avg('life-0')>avg('life-2')*1.35);assert(avg('life-5')>avg('life-7')*2);assert(samples.every(s=>s.fish.filter(f=>['life-3','life-4'].includes(f.id)).every(f=>f.y>=.75&&f.y<=.915)));assert(samples.some(s=>s.fish.some(f=>f.id==='life-3'&&f.pause>0)));assert(d.diagnostics.bursts>0&&d.diagnostics.pauses>0);pass('45 秒實際行為：快速孔雀／斑馬、慢金魚／神仙、鼠魚巡底停頓',{guppy:avg('life-0'),goldfish:avg('life-2'),zebra:avg('life-5'),angel:avg('life-7'),bursts:d.diagnostics.bursts,pauses:d.diagnostics.pauses});fs.writeFileSync(path.join(OUT,'behavior.json'),JSON.stringify({samples,diagnostics:d.diagnostics},null,2));
 // Full fish do not chase; hungry bottom fish finish sinking food.
 await behavior.context.close();const fed=fixture();fed.fishes=[base.fishes[0],base.fishes[1],base.fishes[2]].map((f,i)=>({...f,hunger:i===2?25:100}));const floor=await create({state:fed});await floor.p.locator('#feed').click();await floor.p.locator('#food-type').selectOption('sinking');const box=await floor.p.locator('#tank').boundingBox();let rt=(await read(floor.p)).runtime.find(r=>r.id===fed.fishes[2].id);await floor.p.touchscreen.tap(box.x+box.width*rt.x,box.y+150);await advance(floor.p,800);assert.equal((await read(floor.p)).food.length,3);assert((await read(floor.p)).runtime.filter(r=>r.id!==fed.fishes[2].id).every(r=>r.behavior!=='追食'));await advance(floor.p,24000);d=await read(floor.p);assert(d.state.fishes[2].hunger>30);assert(d.diagnostics.eaten>0);pass('已飽魚不搶食，鼠魚吃下沉到底部的飼料');await floor.context.close();
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(OUT,'additional-results.json'),JSON.stringify({at:new Date().toISOString(),results,errors},null,2));await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1);});
