/* One hour of normal game state. Only the clock and user input advance progress.
   100 ms RAF cadence uses the shipped delta-time limit: 36,000 real simulation steps,
   with no changes to CONFIG, money, growth, XP, unlocks or fish state. */
const {harness}=require('./v03-harness.cjs'),assert=require('node:assert/strict');
(async()=>{const h=await harness(8783),{create,read,advance,shop,closeDialog,pass,shot}=h;const {p,context}=await create({cadence:100,touch:true});let d=await read(p);assert(!d.config.TEST_MODE);assert.equal(d.config.GROWTH_SCALE,1);assert.equal(d.state.coins,20);const initial=structuredClone(d.state),trace=[],actions=[];let firstPurchase=null,firstUpgrade=null,secondUpgrade=null,phaseOne=0,phaseTwo=0;const early=['guppy','zebra','molly'],later=['angel','whitecloud','swordtail','cardinal'];const boughtDecor=new Set();
 async function act(label,extra={}){const s=(await read(p)).state;actions.push({seconds:+s.stats.playSeconds.toFixed(1),action:label,...extra});}
 async function feed(){d=await read(p);const count=Math.min(5,Math.max(3,Math.ceil(d.state.fishes.length/3)));await p.locator('#feed').click();const box=await p.locator('#tank').boundingBox();for(let i=0;i<count;i++){await p.locator('#food-type').selectOption(i===count-1?'sinking':'normal');await p.touchscreen.tap(box.x+box.width*(.16+.68*i/(count-1)),box.y+55);await advance(p,720);}await p.locator('#stop-feed').click();await act('feed',{drops:count});}
 async function buyFish(id){d=await read(p);if(d.state.coins<d.species[id].price||d.state.level<d.species[id].unlockLevel||d.state.fishes.length>=d.state.tankCapacity)return false;await shop(p);await p.locator(`[data-species="${id}"]`).click();await closeDialog(p);await act('buy-fish',{species:id,price:d.species[id].price});if(firstPurchase===null)firstPurchase=(await read(p)).state.stats.playSeconds;return true;}
 async function buyDecor(id,place=false){d=await read(p);if(boughtDecor.has(id)||d.state.coins<d.decorations[id].price)return false;await shop(p,'decor');await p.locator(`[data-buy-decor="${id}"]`).click();if(place){await p.locator(`[data-place-decor="${id}"]`).click();await p.locator('#edit-done').click();}else await closeDialog(p);boughtDecor.add(id);await act('buy-decor',{decoration:id,price:d.decorations[id].price});return true;}
 async function claim(){await p.locator('#tank-menu').click();await p.getByRole('button',{name:'永久成就',exact:true}).click();for(const id of ['firstPurchase','firstAdult','fiveSpecies','fiveDecor','plantGarden','clearWater','eightFish','expandedTank']){const b=p.locator(`[data-claim="${id}"]`);if(await b.isEnabled()){await b.click();await act('claim-achievement',{id});}}await closeDialog(p);}
 await feed();await p.locator('#roster').click();await p.locator('.roster-item').first().click();await shop(p);await closeDialog(p);let nextFeed=120,nextClaim=300,nextSample=120;
 while((await read(p)).state.stats.playSeconds<3600-.1){d=await read(p);await advance(p,Math.min(30000,Math.max(100,Math.round((3600-d.state.stats.playSeconds)*1000))));d=await read(p);if(d.state.drops.length)await p.locator('#collect-all').click();d=await read(p);const t=d.state.stats.playSeconds;
  if(t>=nextFeed&&(Math.min(...d.state.fishes.map(f=>f.hunger))<55||d.state.fishes.reduce((n,f)=>n+f.hunger,0)/d.state.fishes.length<72)){await feed();nextFeed=t+120;}
  if(d.state.waterQuality<68){await p.locator('#clean').click();await act('clean');await advance(p,2300);}
  if(t>=nextClaim){await claim();nextClaim=t+300;}
  d=await read(p);
  if(t<1200&&phaseOne<early.length){if(await buyFish(early[phaseOne]))phaseOne++;}
  if(t>=600&&!boughtDecor.has('smallplant'))await buyDecor('smallplant',true);
  if(t>=900&&!boughtDecor.has('white'))await buyDecor('white');
  if(t>=1500&&!boughtDecor.has('tallplant'))await buyDecor('tallplant',true);
  if(t>=1200&&d.state.tankTier===1&&d.state.level>=3&&d.state.coins>=d.tiers[1].price){await p.locator('#tank-menu').click();await p.locator('#upgrade-tank').click();await closeDialog(p);firstUpgrade=(await read(p)).state.stats.playSeconds;await act('upgrade',{tier:2});}
  d=await read(p);
  if(d.state.tankTier>=2&&phaseTwo<later.length&&t>=firstUpgrade+180){if(await buyFish(later[phaseTwo]))phaseTwo++;}
  if(d.state.tankTier>=2&&t>=2400&&!boughtDecor.has('moss'))await buyDecor('moss',true);
  d=await read(p);
  if(d.state.tankTier===2&&d.state.level>=4&&d.state.coins>=d.tiers[2].price){await p.locator('#tank-menu').click();await p.locator('#upgrade-tank').click();await closeDialog(p);secondUpgrade=(await read(p)).state.stats.playSeconds;await act('upgrade',{tier:3});}
  d=await read(p);if(d.state.stats.playSeconds>=nextSample){const sample={seconds:+d.state.stats.playSeconds.toFixed(1),coins:d.state.coins,fish:d.state.fishes.length,known:Object.keys(d.state.collection).length,level:d.state.level,xp:d.state.xp,tier:d.state.tankTier,water:+d.state.waterQuality.toFixed(1),variants:d.state.unlockedVariants.length,decor:d.state.placedDecorations.length,stages:d.state.fishes.map(f=>({species:f.species,growth:+f.growth.toFixed(2),hunger:+f.hunger.toFixed(1)}))};trace.push(sample);console.log('NORMAL 60',JSON.stringify(sample));nextSample+=120;}
 }
 await claim();d=await read(p);const final=d.state;await shot(p,'normal-60-minutes');assert(firstPurchase>=180&&firstPurchase<=360,`first fish ${firstPurchase}`);assert(firstUpgrade>=1500&&firstUpgrade<=2100,`first upgrade ${firstUpgrade}`);assert(final.stats.playSeconds>=3599&&final.stats.playSeconds<=3610);assert(final.fishes.length>=8);assert(Object.keys(final.collection).length>=7);assert(final.tankTier>=2&&final.tankTier<4);assert(final.unlockedVariants.length<Object.keys(d.variants).length);assert(!final.achievements.companionship.completed);assert(final.level<5,'new-player final species should remain a later goal');assert(final.waterQuality>=45);assert(!d.saveBlocked);if(secondUpgrade!==null)assert(secondUpgrade>=3000&&secondUpgrade<=4200,`second upgrade ${secondUpgrade}`);
 await p.locator('#settings').click();await p.getByRole('button',{name:'存檔',exact:true}).click();const saved=(await read(p)).state;await p.reload();const restored=(await read(p)).state;assert.equal(restored.coins,saved.coins);assert.equal(restored.tankTier,saved.tankTier);assert.deepEqual(restored.placedDecorations,saved.placedDecorations);assert.deepEqual(restored.unlockedVariants,saved.unlockedVariants);assert.deepEqual(restored.achievements,saved.achievements);assert.deepEqual(h.errors,[]);
 let extension=[];if(secondUpgrade===null){while((await read(p)).state.stats.playSeconds<4200){await advance(p,30000);d=await read(p);if(d.state.drops.length)await p.locator('#collect-all').click();if(Math.min(...d.state.fishes.map(f=>f.hunger))<55)await feed();d=await read(p);if(d.state.coins>=d.tiers[2].price){await p.locator('#tank-menu').click();await p.locator('#upgrade-tank').click();await closeDialog(p);secondUpgrade=(await read(p)).state.stats.playSeconds;await act('upgrade',{tier:3});break;}extension.push({seconds:d.state.stats.playSeconds,coins:d.state.coins});}assert(secondUpgrade>=3000&&secondUpgrade<=4200,`second upgrade ${secondUpgrade}`);}
 const evidence={at:new Date().toISOString(),mode:'normal',clock:'Playwright deterministic virtual clock, 100 ms RAF callbacks and the shipped delta-time simulation; 36,000 normal simulation steps; no state or CONFIG cheats',initial,firstPurchase,firstUpgrade,secondUpgrade,trace,extension,actions,final:saved,checks:{normalConfig:true,sixtyMinutes:true,firstFish3to6Minutes:true,firstUpgrade25to35Minutes:true,secondUpgradeWithin50to70Minutes:true,remainingCollectionGoals:true,remainingTankUpgrade:true,remainingAchievements:true,refreshPersistence:true},errors:h.errors};h.saveResults('normal-60-minute-results',evidence);pass('完整 60 分鐘正式經濟、養成、布置、升級、收藏與刷新',{firstPurchase,firstUpgrade,secondUpgrade,fish:final.fishes.length,known:Object.keys(final.collection).length,tier:final.tankTier,coins:final.coins});await context.close();await h.close();
})().catch(e=>{console.error(e);process.exit(1)});
