/* Published Pages smoke test. All local saves live in isolated browser contexts. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'../..'),OUT=process.env.AQUARIUM_ARTIFACTS||path.join(ROOT,'artifacts/aquarium-v03');
const BASE=process.env.AQUARIUM_BASE_URL||'https://ff41009tw52-rgb.github.io/mimi-cream-farm/',KEY='aquarium_game_save_v3';
// Test-only: managed HTTPS interception requires this context override when a proxy exists.
const proxyUrl=process.env.HTTPS_PROXY||process.env.HTTP_PROXY;
const proxy=proxyUrl?(()=>{const u=new URL(proxyUrl);return {server:u.origin,...(u.username?{username:decodeURIComponent(u.username),password:decodeURIComponent(u.password)}:{})};})():undefined;
(async()=>{
 fs.mkdirSync(OUT,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.AQUARIUM_CHROMIUM,proxy,args:['--no-sandbox','--disable-dev-shm-usage']});
 const errors=[],failed=[],results=[];const read=p=>p.evaluate(()=>aquariumDebug());
 const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)failed.push({url:r.url(),status:r.status()});});};
 const create=async(size={width:1440,height:960})=>{const context=await browser.newContext({ignoreHTTPSErrors:!!proxy,viewport:size,hasTouch:true,acceptDownloads:true});const p=await context.newPage();watch(p);return {p,context};};
 const fresh=await create();assert.equal((await fresh.p.goto(BASE+'aquarium-v0.3.html?debug=1')).status(),200);let d=await read(fresh.p);assert.equal(d.state.coins,20);assert.equal(d.state.schemaVersion,3);assert.equal(d.state.fishes.length,3);assert.equal(Object.keys(d.species).length,10);assert.equal(d.config.TEST_MODE,false);
 await fresh.p.locator('#feed').tap();await fresh.p.locator('#tank').tap({position:{x:150,y:65}});assert.equal((await read(fresh.p)).state.onboarding.step,1);await fresh.p.locator('#stop-feed').tap();await fresh.p.locator('#roster').tap();await fresh.p.locator('.roster-item').first().tap();await fresh.p.locator('#shop').tap();assert((await read(fresh.p)).state.onboarding.completed);await fresh.p.locator('#dialog-close').tap();await fresh.p.reload();assert((await read(fresh.p)).state.onboarding.completed);await fresh.p.screenshot({path:path.join(OUT,'online-main.png'),fullPage:true});results.push({test:'published-normal-start-onboarding-save',passed:true});await fresh.context.close();
 // Preserve the exact V0.2 payload and manual snapshot in the real website origin.
 const old=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/v02-real-save.json'))),manual=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/v02-real-manual.json')));old.savedAt=Date.now();manual.savedAt=Date.now();const oldText=JSON.stringify(old),manualText=JSON.stringify(manual);
 const migration=await create();await migration.p.addInitScript(({oldText,manualText})=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem('aquarium_game_save_v2',oldText);localStorage.setItem('aquarium_game_save_v2_manual',manualText);sessionStorage.setItem('seeded','1');}},{oldText,manualText});
 await migration.p.goto(BASE+'aquarium-v0.3.html?debug=1');d=await read(migration.p);assert.equal(d.state.coins,old.coins);assert.equal(d.state.level,old.level);assert.deepEqual(d.state.fishes.map(f=>[f.id,f.name]),old.fishes.map(f=>[f.id,f.name]));d.state.fishes.forEach((f,i)=>assert(Math.abs(f.growth-old.fishes[i].growth)<1));assert.equal(d.state.substrate,old.substrate);assert.equal(JSON.parse(await migration.p.evaluate(k=>localStorage.getItem(k+'_manual'),KEY)).schemaVersion,3);
 await migration.p.locator('#roster').tap();await migration.p.locator('.roster-item').first().tap();await migration.p.locator('#rename').tap();await migration.p.locator('#fish-new-name').fill('悠悠三號');await migration.p.getByRole('button',{name:'保存名字'}).tap();await migration.p.locator('#close-card').tap();await migration.p.locator('#tank-menu').tap();await migration.p.getByRole('button',{name:'編輯魚缸',exact:true}).tap();await migration.p.locator('[data-decor-id]').first().tap();await migration.p.locator('#edit-right').tap();const placed=(await read(migration.p)).state.placedDecorations;await migration.p.locator('#edit-done').tap();await migration.p.reload();d=await read(migration.p);assert.equal(d.state.fishes[0].name,'悠悠三號');assert.deepEqual(d.state.placedDecorations,placed);assert.equal(await migration.p.evaluate(()=>localStorage.getItem('aquarium_game_save_v2')),oldText);assert.equal(await migration.p.evaluate(()=>localStorage.getItem('aquarium_game_save_v2_manual')),manualText);
 await migration.p.goto(BASE+'aquarium-v0.3-standalone.html?debug=1');assert.equal((await read(migration.p)).state.fishes[0].name,'悠悠三號');assert.deepEqual((await read(migration.p)).state.placedDecorations,placed);const backup=(await read(migration.p)).state;results.push({test:'published-v02-auto-manual-migration-rename-edit-refresh-standalone',passed:true});await migration.context.close();
 const recovery=await create();await recovery.p.addInitScript(({key,backup})=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem(key,'{bad');localStorage.setItem(key+'_manual',JSON.stringify(backup));sessionStorage.setItem('seeded','1');}},{key:KEY,backup});await recovery.p.goto(BASE+'aquarium-v0.3.html?debug=1');assert((await read(recovery.p)).saveBlocked);await recovery.p.locator('#settings').tap();await recovery.p.getByRole('button',{name:'讀檔',exact:true}).tap();await recovery.p.getByRole('button',{name:'確定讀取',exact:true}).tap();assert(!(await read(recovery.p)).saveBlocked);await recovery.p.reload();assert(!(await read(recovery.p)).saveBlocked);assert.equal((await read(recovery.p)).state.fishes[0].name,'悠悠三號');await recovery.p.screenshot({path:path.join(OUT,'online-recovery.png'),fullPage:true});results.push({test:'published-corrupt-auto-valid-manual-recovery-persists',passed:true});await recovery.context.close();
 // Native V0.1 page produces its own original save, then V0.3 migrates that save.
 const v1=await create();assert.equal((await v1.p.goto(BASE+'aquarium-game.html')).status(),200);const oldNames=await v1.p.evaluate(()=>JSON.parse(localStorage.getItem('aquarium_game_save_v1')).fishes.map(f=>[f.id,f.name]));await v1.p.goto(BASE+'aquarium-v0.3.html?debug=1');assert.deepEqual((await read(v1.p)).state.fishes.map(f=>[f.id,f.name]),oldNames);assert.equal((await read(v1.p)).state.coins,120);results.push({test:'published-native-v01-chain-migration',passed:true});await v1.context.close();
 for(const size of [{width:1024,height:768},{width:820,height:1180},{width:390,height:844}]){const touch=await create(size);await touch.p.goto(BASE+'aquarium-v0.3.html');await touch.p.locator('#onboarding-skip').tap();assert(await touch.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const id of ['feed','shop','clean']){const box=await touch.p.locator('#'+id).boundingBox();assert(box.width>=44&&box.height>=44);}
  await touch.p.locator('#shop').tap();await touch.p.locator('#tab-decor').tap();await touch.p.locator('#dialog-close').tap();await touch.p.locator('#encyclopedia').tap();await touch.p.locator('#dialog-close').tap();await touch.p.screenshot({path:path.join(OUT,'online-'+size.width+'.png'),fullPage:true});results.push({test:'published-touch-'+size.width+'x'+size.height,passed:true});await touch.context.close();}
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync(path.join(OUT,'online-results.json'),JSON.stringify({at:new Date().toISOString(),base:BASE,browser:browser.version(),results,errors,failedRequests:failed},null,2));await browser.close();console.log('PASS published V0.3: normal start, onboarding, migration, rename/edit/save, standalone, three touch viewports');
})().catch(e=>{console.error(e);process.exit(1)});
