/* Mouse, trusted emulated touch and pen input; these are viewport tests, not devices. */
const {harness}=require('./v03-harness.cjs'),assert=require('node:assert/strict');
(async()=>{const h=await harness(8784),{create,read,shop,closeDialog,shot,pass}=h;const first=await create({seed:{aquarium_game_save_v2:JSON.stringify(h.legacy())}});const base=(await read(first.p)).state;await first.context.close();base.coins=9000;base.xp=1100;base.level=5;base.savedAt=Date.now();
 async function touchDrag(p,b,dx,dy=0){const client=await p.context().newCDPSession(p),x=b.x+b.width/2,y=b.y+b.height*.6;await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=8;i++)await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/8,y:y+dy*i/8}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await client.detach();}
 for(const size of [{width:1024,height:768},{width:820,height:1180},{width:390,height:844}]){
  const {p,context}=await create({size,state:base,touch:true});await shop(p);for(const id of ['angel','whitecloud'])await p.locator(`[data-species="${id}"]`).click();await closeDialog(p);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));let box=await p.locator('#tank').boundingBox();assert(box.height>=size.height*(size.width===820?.54:.4));for(const id of ['feed','shop','clean']){const b=await p.locator('#'+id).boundingBox();assert(b.width>=44&&b.height>=44&&b.y+b.height<=size.height,`${size.width} ${id} out of viewport`);}await shot(p,size.width===1024?'13-tablet-1024':size.width===820?'14-portrait-820':'15-phone-390');
  await shop(p,'decor');assert(await p.evaluate(()=>document.querySelector('#dialog').scrollWidth<=document.querySelector('#dialog').clientWidth+2));await p.locator('[data-buy-decor="cave"]').click();await p.locator('[data-place-decor="cave"]').click();await p.locator('#edit-done').click();await p.locator('#tank-menu').click();await p.getByRole('button',{name:'編輯魚缸',exact:true}).click();let state=(await read(p)).state;const plant=state.placedDecorations.find(i=>i.decoration==='smallplant'&&i.normX<.3),handle=p.locator(`[data-decor-id="${plant.id}"]`);box=await handle.boundingBox();const scroll=await p.evaluate(()=>scrollY);await touchDrag(p,box,Math.min(95,size.width*.18));state=(await read(p)).state;const moved=state.placedDecorations.find(i=>i.id===plant.id);assert.notEqual(moved.normX,plant.normX);assert.equal(moved.normX,.06+.88*moved.snapIndex/15);assert.equal(await p.evaluate(()=>scrollY),scroll);assert((await read(p)).editing);await p.locator('#edit-left').click();await p.locator('#edit-right').click();const placed=(await read(p)).state.placedDecorations;await p.locator('#edit-done').click();await p.reload();assert.deepEqual((await read(p)).state.placedDecorations,placed);
  // Invalid ground overlap restores the old location and retains the object.
  await p.locator('#tank-menu').click();await p.getByRole('button',{name:'編輯魚缸',exact:true}).click();state=(await read(p)).state;const cave=state.placedDecorations.find(d=>d.decoration==='cave'),rock=state.placedDecorations.find(d=>d.decoration==='smallrock');box=await p.locator(`[data-decor-id="${cave.id}"]`).boundingBox();const tank=await p.locator('#tank').boundingBox();await touchDrag(p,box,(rock.normX-cave.normX)*tank.width);assert.equal((await read(p)).state.placedDecorations.find(d=>d.id===cave.id).normX,cave.normX);assert.match(await p.locator('#toast').innerText(),/有點擠/);await p.locator('#edit-store').click();assert(!(await read(p)).state.placedDecorations.some(d=>d.id===cave.id));assert.equal((await read(p)).state.purchasedDecorations.cave,1);await p.locator('#edit-done').click();
  await p.locator('#encyclopedia').click();await p.locator('[data-entry="guppy"]').getByRole('button').click();await closeDialog(p);await p.locator('#roster').click();await p.locator('.roster-item').first().click();box=await p.locator('#fish-card').boundingBox();const t=await p.locator('#tank').boundingBox();assert(box.height<t.height&&box.width<t.width*.6);assert(box.x+box.width<=size.width&&box.y+box.height<=t.y+t.height);await p.locator('#close-card').click();
  // Ensure blank water remains scrollable in edit mode; a tall page is a scroll fixture only.
  await p.locator('#tank-menu').click();await p.getByRole('button',{name:'編輯魚缸',exact:true}).click();await p.evaluate(()=>document.body.style.minHeight='2000px');box=await p.locator('#tank').boundingBox();const y=Math.min(size.height-110,box.y+box.height*.45);await touchDrag(p,{x:box.x+box.width*.45,y:y-10,width:10,height:10},0,-120);await p.waitForTimeout(200);assert(await p.evaluate(()=>scrollY>0));await p.evaluate(()=>{document.body.style.minHeight='';scrollTo(0,0);});await p.locator('#edit-done').click();await context.close();pass(`${size.width}×${size.height}：8 魚、觸控選取/拖動/snap/箭頭/收起/刷新、重疊保護、普通頁面捲動、商店/圖鑑/魚卡、不爆版`);
 }
 const pen=await create({state:base});await pen.p.locator('#tank-menu').click();await pen.p.getByRole('button',{name:'編輯魚缸',exact:true}).click();const item=(await read(pen.p)).state.placedDecorations.find(i=>i.decoration==='smallplant'&&i.normX<.3),box=await pen.p.locator(`[data-decor-id="${item.id}"]`).boundingBox(),c=await pen.context.newCDPSession(pen.p),x=box.x+box.width/2,y=box.y+box.height*.7;await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y,pointerType:'pen'});await c.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1,pointerType:'pen'});await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',x:x+110,y,buttons:1,pointerType:'pen'});await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:x+110,y,button:'left',clickCount:1,pointerType:'pen'});assert.notEqual((await read(pen.p)).state.placedDecorations.find(i=>i.id===item.id).normX,item.normX);await c.detach();await pen.context.close();pass('Pointer Events 手寫筆事件路徑亦可左右移動裝飾');assert.deepEqual(h.errors,[]);h.saveResults('responsive-results',{results:h.results,errors:h.errors,physicalDevices:'尚未進行',studentPlaytest:'尚未進行'});await h.close();
})().catch(e=>{console.error(e);process.exit(1)});
